Changed to running tests in subshell

diff --git a/muse_root/munit/ctl/bootstrap b/muse_root/munit/ctl/bootstrap
--- a/muse_root/munit/ctl/bootstrap
+++ b/muse_root/munit/ctl/bootstrap
@@ -1,9 +1,9 @@
 #! /bin/bash
 ##############################################################
 ##
-## Name         :   munit.bootstrap
+## Name         :   bootstrap
 ## Author       :   Bradley Atkins
-## Description  :   Environment vars for MUNIT
+## Description  :   Environment vars for MUNIT and common funcs
 ## Date         :   02/08/2015
 ## Status       :   Reviewed    [n]
 ##                  Tested      [n]
@@ -16,18 +16,19 @@ set -a
     # MUNIT test definitions
     #======================================
     eval MU_MUNIT_ROOT="${MU_MAP_DIRS[1]}"
-    MU_TEST_DEFS="${MU_MUNIT_ROOT}/test"
 
     #======================================
     # Path to MUNIT libraries
     #======================================
     MU_LIB="${MU_MUNIT_ROOT}/lib"
+    MU_CTL="${MU_MUNIT_ROOT}/ctl"
+    MU_TST="${MU_MUNIT_ROOT}/tst"
 
     #======================================
     # MUNIT control files
     #======================================
-    MU_CTL="${MU_MUNIT_ROOT}/ctl"
     MU_TMP="/var/tmp/munit/tmp"
+    MU_RPT="/var/tmp/munit/rpt"
     MU_MUNIT_MAP="${MU_TMP}/mu_test_map"
 
     #======================================
@@ -35,18 +36,49 @@ set -a
     #======================================
     MU_TEST_LOG="${MU_TMP}/mu_test_log"
     MU_TEST_BUF="${MU_TMP}/mu_test_buf"
+    MU_TEST_HED="${MU_TMP}/mu_test_hed"
     MU_ERROR_BUF="${MU_TMP}/mu_error_buf"
+    MU_ERROR_IDX="${MU_TMP}/mu_error_idx"   ## Index for error report
 
     #======================================
     # Global Constants
     #======================================
     MC_NAME_SEP="."
     MU_MENU_LINE_LEN=25
-    MU_HEAD_LINE_LEN=100
+    MU_HEAD_LINE_LEN=75
 
     #======================================
-    # Runtime vars
+    # Run Array for Test names
     #======================================
+    declare -a MU_RUN_ORDER
+
+##############################################################
+##
+## Name         :   mu_validate_environment
+## Author       :   Bradley Atkins
+## Description  :   Check we have sensible environment vars
+## Date         :   07/08/2015
+## Args         :   
+## Status       :   Reviewed    [n]
+##                  Tested      [n]
+##                  Released    [n]
+##                  Disabled    [n]
+##############################################################
+mu_validate_environment()
+{
+    [[ "${MU_MUNIT_ROOT}" =~ ^/.* ]] || die "MU_MUNIT_ROOT validation failed (${FUNCNAME})"
+    [[ "${MU_LIB}" =~ ^/.*/lib ]] || die " MU_LIB validation failed (${FUNCNAME})"
+    [[ "${MU_CTL}" =~ ^/.*/ctl ]] || die "MU_CTL validation failed (${FUNCNAME})"
+    [[ "${MU_TST}" =~ ^/.*/tst ]] || die "MU_CTL validation failed (${FUNCNAME})"
+    [[ "${MU_TMP}" =~ ^/.*/munit/tmp ]] || die "MU_TMP validation failed (${FUNCNAME})"
+    [[ "${MU_MUNIT_MAP}" =~ ^/.*/mu_test_map ]] || die "MU_MUNIT_MAP validation failed (${FUNCNAME})"
+    [[ "${MU_TEST_LOG}" =~ ^/.*/mu_test_log ]] || die "MU_TEST_LOG validation failed (${FUNCNAME})"
+    [[ "${MU_TEST_BUF}" =~ ^/.*/mu_test_buf ]] || die "MU_TEST_BUF validation failed (${FUNCNAME})"
+    [[ "${MU_TEST_HED}" =~ ^/.*/mu_test_hed ]] || die "MU_TEST_HED validation failed (${FUNCNAME})"
+    [[ "${MU_ERROR_BUF}" =~ ^/.*/mu_error_buf ]] || die "MU_ERROR_BUF validation failed (${FUNCNAME})"
+    [[ -n "${MC_NAME_SEP}" ]] || die "MC_NAME_SEP validation failed (${FUNCNAME})"
+    [[ "${MU_MENU_LINE_LEN}" =~ ^[[:digit:]]+$ ]] || die "MU_MENU_LINE_LEN validation failed (${FUNCNAME})"
+    [[ "${MU_HEAD_LINE_LEN}" =~ ^[[:digit:]]+$ ]] || die "MU_HEAD_LINE_LEN validation failed (${FUNCNAME})"
     MU_ERRORS=0
     MU_FAILURES=0
     MU_TESTS=0
@@ -54,28 +86,36 @@ set -a
     MU_CMD_LINE=""
     MU_TEST_NAMES=""
     MU_CURRENT_PROJECT=""
-
     TMPFIL1=""
     TMPFILE2=""
     TMPFILE3=""
-
     TESTFILE=""
-
-    #======================================
-    # Run Array for Test names
-    #======================================
-    declare -a MU_RUN_ORDER
-    MU_RUN_INDEX=0
-    MU_NUM_TESTS=0
-    MU_ERROR_INDEX=0
-    MU_FAIL_INDEX=0
-
     #======================================
     # Reporting
     #======================================
     MU_FAILURE_LINE_PRINTED=false
-
-
+    MU_ERROR_LINE_PRINTED=false
+}
+##############################################################
+##
+## Name         :   mu_init
+## Author       :   Bradley Atkins
+## Description  :   Setup the run environment
+## Date         :   07/08/2015
+## Args         :   
+## Status       :   Reviewed    [n]
+##                  Tested      [n]
+##                  Released    [n]
+##                  Disabled    [n]
+##############################################################
+mu_init()
+{
+    mkdir -p "${MU_TMP}" 2>/dev/null 
+    mkdir -p "${MU_RPT}" 2>/dev/null
+    [[ -d "${MU_TMP}" ]] || die "Failed to create tmp dir (${MU_TMP}) (${FUNCNAME})"
+    [[ -d "${MU_RPT}" ]] || die "Failed to create tmp dir (${MU_RPT}) (${FUNCNAME})"
+    printf "%s" "0" > "${MU_ERROR_IDX}"
+}
 ##############################################################
 ##
 ## Name         :   usage
@@ -88,12 +128,16 @@ set -a
 ##############################################################
 usage()
 {
+    local HEADLINE= OFS=$(( MU_HEAD_LINE_LEN / 3 ))
+    mu_gen_line "=" "${MU_HEAD_LINE_LEN}" HEADLINE
+
+    printf "%s\n" "${HEADLINE}"
+    printf "\n%-${OFS}s%s\n\n" "" "MUNIT Usage Guide"
+    printf "\t%s\n" "usage: ${0##*/} [-option] [file] [file] ..."
     printf "\n"
-    printf "\t%s\n" "usage: ${0##*/} [-option] file file ..."
-    printf "\n"
-    printf "\t%s\n" "${0##*/} <test name/s>         :Run a test suite"
-    printf "\t%s\n" "${0##*/} -a                    :Run all tests in current project"
-    printf "\t%s\n" "${0##*/} -s                    :Select current project and tests"
+    printf "\t%s\n" "${0##*/} <test name/s>  :Run test suite/s"
+    printf "\t%s\n" "${0##*/} -s             :Select project and test/s"
+    printf "\n%s\n" "${HEADLINE}"
     exit
 }
 ##############################################################
@@ -258,26 +302,17 @@ mu_gen_line()
 ##############################################################
 validate_cmd_line()
 {
+    [[ $# -eq 0 ]] && usage
+
+    #======================================
+    # Validate
+    #======================================
     local FILE= OPT= PRJS= HLINE=
     mu_gen_line "=" "${MU_MENU_LINE_LEN}" HLINE
 
     while [[ $# -gt 0 ]]
     do
         case ${1} in
-            -a|--all)
-                
-                shift
-                [[ $# -gt 0 ]] && die "Usage. Option (${1}) requires no arguments"
-
-                #======================================
-                # User wants to run all tests
-                #======================================
-                for FILE in $(find "${MU_TEST_DEFS}" -type f -name mu_\*)
-                do
-                    MU_TEST_NAMES="${MU_TEST_NAMES} $(basename ${FILE})"
-                done
-                [[ -n "${MU_TEST_NAMES}" ]] || die "No tests found in (${MU_TEST_DEFS})"
-            ;;
             mu_*)
                 #======================================
                 # User wants to run specific test/s
@@ -297,7 +332,7 @@ validate_cmd_line()
                 # List all projects in a menu format.
                 # Set current project from selection.
                 #======================================
-                if [[ -n $(ls -d test/* 2>/dev/null | awk '{print $NF}' FS='/') ]]
+                if [[ -n $(ls -d tst/* 2>/dev/null | awk '{print $NF}' FS='/') ]]
                 then
                     clear
                     echo "${HLINE}"
@@ -305,7 +340,7 @@ validate_cmd_line()
                     echo "${HLINE}"
 
                     PS3='Set working project: '
-                    OPTIONS=($(ls -d test/* 2>/dev/null | awk '{print $NF}' FS='/') "Quit")
+                    OPTIONS=($(ls -d tst/* 2>/dev/null | awk '{print $NF}' FS='/') "Quit")
                     select OPT in "${OPTIONS[@]}"
                     do
                         ## Choice out of range
@@ -323,7 +358,7 @@ validate_cmd_line()
                                 #======================================
                                 MU_CURRENT_PROJECT="${OPT}"
                                 clear
-                                TESTS="$(ls -f test/"${MU_CURRENT_PROJECT}"/mu_test* 2>/dev/null | awk '{print $NF}' FS='/')"
+                                TESTS="$(ls -f tst/"${MU_CURRENT_PROJECT}"/mu_test* 2>/dev/null | awk '{print $NF}' FS='/')"
                                 if [[ -n "${TESTS}" ]] 
                                 then
                                     echo "${HLINE}"
@@ -375,13 +410,6 @@ validate_cmd_line()
                     echo "${HLINE}"
                     exit
                 fi
-            ;;
-            -t)
-                #======================================
-                # List all tests sorted by project then
-                # name in menu form. Run selection.
-                #======================================
-                echo "TODO"
             ;;
         esac
     done
@@ -506,21 +534,37 @@ mu_create_test_files()
             then
                 #======================================
                 # Record the testname in the run array
-                # TODO refactor for project name
                 #======================================
                 TEST_NAME=${MU_CURRENT_PROJECT}${MC_NAME_SEP}${TEST_SUITE}${MC_NAME_SEP}$(echo "${LINE}" | cut -d"=" -f2)
                 MU_RUN_ORDER[$(( MU_RUN_INDEX += 1 ))]="${TEST_NAME}"
                 TEST_FILE="${MU_TMP}/${TEST_NAME}"
                 printf "%s\n" "#! /bin/bash" > "${TEST_FILE}"
+                [[ "${MU_DEBUG_TEST}" == "TRUE" ]] && printf "%s\n" "set -x" >> "${TEST_FILE}"
                 printf "%s\n" "export THIS_TEST_NAME=${TEST_NAME}" >> "${TEST_FILE}"
+                printf "%s\n" "export MU_TMP=${MU_TMP}" >> "${TEST_FILE}"
+                printf "%s\n" "export MU_RPT=${MU_RPT}" >> "${TEST_FILE}"
+                printf "%s\n" "export MU_ERROR_IDX=${MU_ERROR_IDX}" >> "${TEST_FILE}"
+                printf "%s\n" "export MU_TEST_BUF=${MU_TEST_BUF}" >> "${TEST_FILE}"
+                #======================================
+                # Add source of all libraries
+                #======================================
+                for f in $(ls "${MU_LIB}/"*.funcs)
+                do
+                    printf "%s\n" "source ${f}" >> "${TEST_FILE}"
+                done
+
                 chmod +x "${TEST_FILE}"
                 MU_NUM_TESTS=$(( MU_NUM_TESTS + 1 ))
+                
+                #======================================
+                # Create a stats file for it
+                #======================================
+                printf "%s" "0 0 0" > "${MU_RPT}/${TEST_NAME}.sts"
+                :>"${MU_RPT}/${TEST_NAME}.rpt"
             else
                 printf "%s\n" "$LINE" | sed '{
-                    s/\(require .*\)/\1 || return 0/
-                    s/\(import .*\)/\1 || return 0/
-                    s/exit/return 0/
-
+                    s/\(require .*\)/\1 || exit 1/
+                    s/\(import .*\)/\1 || exit 1/
                 }' >> "${TEST_FILE}"
             fi
         done < <( awk '/^def/{printf "%s%s\n", "TEST=", $2;next}
diff --git a/muse_root/munit/munit b/muse_root/munit/munit
--- a/muse_root/munit/munit
+++ b/muse_root/munit/munit
@@ -77,19 +77,10 @@ die()
 #======================================
 # Bootstrap
 #======================================
-cd $(echo "$(cd "$(dirname "$0")"; pwd)")
+cd "$(dirname "$0")"
 source ./ctl/user.env
-source ./ctl/munit.bootstrap
-[[ -n "${MU_LOG}" ]] || die "Env variable MU_LOG not set (munit)"
-[[ -n "${MU_MUNIT_ROOT}" ]] || die "Env variable MU_MUNIT_ROOT not set (munit)"
-[[ -n "${MU_TMP}" ]] || die "Env variable MU_TMP not set (munit)"
-[[ -d "${MU_TEST_DEFS}" ]] || die "Env variable MU_TEST_DEFS not a directory (munit)"
-[[ -d "${MU_LIB}" ]] || die "Env variable MU_LIB not a directory (munit)"
-[[ -d "${MU_CTL}" ]] || die "Env variable MU_CTL not a directory (munit)"
-[[ -n "${MU_MUNIT_MAP}" ]] || die "Env variable MU_MUNIT_MAP not set (munit)"
-[[ -n "${MU_TEST_LOG}" ]] || die "Env variable MU_TEST_LOG not set (munit)"
-[[ -n "${MU_TEST_BUF}" ]] || die "Env variable MU_TEST_BUF not set (munit)"
-[[ -n "${MU_ERROR_BUF}" ]] || die "Env variable MU_ERROR_BUF not set (munit)"
+source ./ctl/bootstrap
+mu_validate_environment
 
 #======================================
 # Logging
@@ -113,8 +104,15 @@ mu_log_line "Starting test run - (${MU_RUNID})" "INFO"
 # Create the runtime directories
 #======================================
 mkdir -p "${MU_TMP}"
-[[ -d "${MU_TMP}" ]] || die "Failed to cretae MUNIT TMP directory (${MU_TMP}) (munit)"
+[[ -d "${MU_TMP}" ]] || die "Failed to create MUNIT TMP directory (${MU_TMP}) (munit)"
 rm -rf "${MU_TMP}"/* || die "Cleardown of (${MU_TMP}) failed"
+[[ -d "${MU_RPT}" ]] || die "Failed to create MUNIT report directory (${MU_RPT}) (munit)"
+rm -rf "${MU_RPT}"/* || die "Cleardown of (${MU_RPT}) failed"
+
+#======================================
+# Initialise the run environment
+#======================================
+mu_init
 
 #======================================
 # Create the map files
@@ -128,17 +126,6 @@ mu_create_map_files
 validate_cmd_line "$@"
 [[ "${MU_LOG_LEVEL}" == "DEBUG" ]] && mu_log_line "Command line validated ($@)" "INFO"
 
-#=====================================
-# Include the MUNIT libraries
-#======================================
-include assert-string.funcs
-include assert-integer.funcs
-include assert-float.funcs
-include assert-file.funcs
-include raise.funcs
-include require.funcs
-[[ "${MU_LOG_LEVEL}" == "DEBUG" ]] && mu_log_line "Includes successfully sourced" "INFO"
-
 #======================================
 # Parse the test suites and break out
 # each test into its own exe
@@ -147,22 +134,30 @@ mu_create_test_files
 [[ "${MU_LOG_LEVEL}" == "DEBUG" ]] && mu_log_line "Test files created" "INFO"
 
 #======================================
+# Set some run vars
+#======================================
+printf "%s\n" "Errors:" > "${MU_TEST_BUF}"
+printf "%s\n" "Tests:" > "${MU_TEST_HED}"
+mu_gen_line "=" "${MU_HEAD_LINE_LEN}" HEADLINE
+
+include reporting.funcs
+#======================================
 # Run each test and create each report
 #======================================
 [[ "${MU_LOG_LEVEL}" == "DEBUG" ]] && mu_log_line "Running Tests" "INFO"
-printf "%s\n" "Errors:" > "${MU_TEST_BUF}"
-MU_ERROR_INDEX=0
-mu_gen_line "=" "${MU_HEAD_LINE_LEN}" HEADLINE
-
 MU_RUN_INDEX=0
 while [[ $(( MU_RUN_INDEX += 1 )) -le ${MU_NUM_TESTS} ]]
 do
     MU_TESTS=$(( MU_TESTS +1 ))
     THISTEST=${MU_RUN_ORDER[$MU_RUN_INDEX]}
-    if ! source "${MU_TMP}/${THISTEST}" 2> "${MU_ERROR_BUF}"
+
+    printf "\t%-4d - %s\n" "${MU_TESTS}" "${THISTEST}" >> "${MU_TEST_HED}"
+
+    if ! "${MU_TMP}/${THISTEST}" 2> "${MU_ERROR_BUF}"
     then
+        mu_set_error_index MU_ERROR_INDEX
         MU_ERRORS=$(( MU_ERRORS +1 ))
-        printf "\n\t$(( MU_ERROR_INDEX += 1 )) - %s\n" "${MU_RUN_ORDER[$MU_RUN_INDEX]}" >> "${MU_TEST_BUF}"
+        printf "\n\t${MU_ERROR_INDEX} - %s\n" "${MU_RUN_ORDER[$MU_RUN_INDEX]}" >> "${MU_TEST_BUF}"
         while read LINE
         do
             printf "\t\t%s\n" "${LINE}" >> "${MU_TEST_BUF}"
@@ -170,42 +165,98 @@ do
     fi
 done
 
-#======================================
+#=====================================
 # Concat all of the reports into one
 #======================================
 [[ "${MU_LOG_LEVEL}" == "DEBUG" ]] && mu_log_line "Compiling reports" "INFO"
-printf "%s\n" "${HEADLINE}" > "${MU_TEST_LOG}"
-printf "\t%s\n" "$(date): MUNIT Test Report" >> "${MU_TEST_LOG}"
-printf "\t%s\n" "Project - (${MU_CURRENT_PROJECT})" >> "${MU_TEST_LOG}"
-printf "\t%s\n" "(${MU_NUM_TESTS}) Tests, (${MU_ASSERTIONS}) Assertions, (${MU_FAILURES}) Failures. (${MU_ERRORS}) Errors" >> "${MU_TEST_LOG}"
-printf "%s\n" "${HEADLINE}" >> "${MU_TEST_LOG}"
-[[ ${MU_FAILURES} -gt 0 ]] && printf "%s\n" "Failures:" >> "${MU_TEST_LOG}"
 
+#======================================
+# Print the report header
+#======================================
+OFS=$(( MU_HEAD_LINE_LEN / 6 ))
+printf "%s\n" "${HEADLINE}" > "${MU_TEST_LOG}"
+printf "%-${OFS}s%s\n" "" "$(date): MUNIT Test Report" >> "${MU_TEST_LOG}"
+printf "%-${OFS}s%s\n" "" "Project - (${MU_CURRENT_PROJECT})" >> "${MU_TEST_LOG}"
+printf "%-${OFS}s%s\n" "" "(${MU_NUM_TESTS}) Tests, (_MU_ASSERTIONS_) Assertions, (_MU_FAILURES_) Failures. (_MU_ERRORS_) Errors" >> "${MU_TEST_LOG}"
+printf "%s\n" "${HEADLINE}" >> "${MU_TEST_LOG}"
+
+#======================================
+# List of tests that were run
+#======================================
+if ${MU_DISPLAY_TEST_LIST}
+then
+    cat "${MU_TEST_HED}" >> "${MU_TEST_LOG}"
+    echo >> "${MU_TEST_LOG}"
+fi
+
+#======================================
+# Handle adding any failures to rpt
+#======================================
 MU_FAIL_INDEX=0
 MU_RUN_INDEX=0
+
 while [[ $(( MU_RUN_INDEX += 1 )) -le ${MU_NUM_TESTS} ]]
 do
-    THISRPT="${MU_TMP}/${MU_RUN_ORDER[$MU_RUN_INDEX]}.rpt"
+    #======================================
+    # Report and stats files
+    #======================================
+    THISRPT="${MU_RPT}/${MU_RUN_ORDER[$MU_RUN_INDEX]}.rpt"
+    THISSTS="${MU_RPT}/${MU_RUN_ORDER[$MU_RUN_INDEX]}.sts"
+    [[ -r "${THISRPT}" ]] || die "Report (${THISRPT}) not found"
+    [[ -r "${THISSTS}" ]] || die "Stats file (${THISSTS}) not found"
+    #======================================
+    # If report not empty then contains 
+    # failures so read into master rpt
+    #======================================
     if [[ -s "${THISRPT}" ]]
     then
+        #======================================
+        # If this is the first fail then print
+        #======================================
+        if ! "${MU_FAILURE_LINE_PRINTED}"
+        then
+            printf "%s\n" "Failures:" >> "${MU_TEST_LOG}"
+            MU_FAILURE_LINE_PRINTED=true
+        fi
+        #======================================
+        # Report name and lines from rpt
+        #======================================
         printf "\n\t$(( MU_FAIL_INDEX += 1 )) - %s\n" "${MU_RUN_ORDER[$MU_RUN_INDEX]}" >> "${MU_TEST_LOG}"
         while read LINE
         do
             printf "\t\t%s\n" "${LINE}" >> "${MU_TEST_LOG}"
         done < "${THISRPT}"
     fi
+    #======================================
+    # Update the global metrics
+    #======================================
+    read assertions failures errors < "${THISSTS}"
+    MU_ASSERTIONS=$(( MU_ASSERTIONS + assertions ))
+    MU_FAILURES=$(( MU_FAILURES + failures ))
+    MU_ERRORS=$(( MU_ERRORS + errors ))
 done
 printf "\n" >> "${MU_TEST_LOG}"
 
+#======================================
+# Update the header with the metrics
+#======================================
+sed -i '{
+    s/_MU_ASSERTIONS_/'${MU_ASSERTIONS}'/
+    s/_MU_FAILURES_/'${MU_FAILURES}'/
+    s/_MU_ERRORS_/'${MU_ERRORS}'/
+}' "${MU_TEST_LOG}"
 
 #======================================
-# Display the test log
+# Display the test report
 #======================================
+clear
 [[ ${MU_ERRORS} -gt 0 ]] && grep -v -A1 '^[[:blank:]]*$' "${MU_TEST_BUF}" | grep -v '^--$' >> "${MU_TEST_LOG}"
 grep -v -A1 '^[[:blank:]]*$' "${MU_TEST_LOG}" | grep -v '^--$'
 
-printf "%s\n" "${HEADLINE}"
-
+if ${MU_DISPLAY_TEST_LIST} || [[ ${MU_ERRORS} -gt 0 ]] || [[ ${MU_FAILURES} -gt 0 ]]
+then
+    printf "%s\n" "${HEADLINE}"
+fi
 [[ "${MU_LOG_LEVEL}" == "DEBUG" ]] && mu_log_line "Run complete for - (${MU_RUNID})" "INFO"
 
 
