Refactor to make more generic. Removed all ref to MUSE

diff --git a/muse_root/munit/ctl/munit_bootstrap b/muse_root/munit/ctl/munit_bootstrap
--- a/muse_root/munit/ctl/munit_bootstrap
+++ b/muse_root/munit/ctl/munit_bootstrap
@@ -17,42 +17,25 @@ set -a
     MU_LOG_LEVEL="DEBUG"
 
     #======================================
-    # SUT
-    #======================================
-    MU_SUT="muse"
-
-    ## TODO Make the muse specific stuff genric
-    MU_SUT_ROOT="/usr/local/bin/muse_root"
-    MU_SUT_DEV_ROOT="/opt/mailcontrol/.muse_dev"
-    
-    #======================================
-    # Paths to the results / ctrl files 
-    # for MUSE
-    #======================================
-    MU_MASTER_RESULTS_ROOT="/var/tmp/muse/run/master"
-    MU_SLAVE_RESULTS_ROOT="/var/tmp/muse/run/slave"
-
-
-    #======================================
     # Logging
     #======================================
     MU_LOG="/var/log/munit/munit.log"
 
     #======================================
-    # Test servers used by MUNIT
+    # MUNIT MAPPED directories. [1] is
+    # always pointing to munit top dir.
+    # The others are used to find any files
+    # in the SUT
     #======================================
-    MU_MASTER_HOST="dev01o"
-    MU_SLAVE_HOST="dev01o"
-
-    #======================================
-    # MUNIT directories
-    #======================================
-    MU_MUNIT_ROOT="/opt/mailcontrol/.muse_dev"
-    MU_TMP="/var/tmp/munit/tmp"
+    declare -a MU_MAP_DIRS
+    MU_MAP_DIRS[1]="$(dirname $0)"
+    MU_MAP_DIRS[2]="/opt/mailcontrol/.muse_dev"
+    MU_MAP_DIRS[3]="/var/opt/muse_root"
 
     #======================================
     # MUNIT test definitions
     #======================================
+    eval MU_MUNIT_ROOT="${MU_MAP_DIRS[1]}"
     MU_TEST_DEFS="${MU_MUNIT_ROOT}/test"
 
     #======================================
@@ -61,15 +44,15 @@ set -a
     MU_LIB="${MU_MUNIT_ROOT}/lib"
 
     #======================================
-    # Path to MUNIT control files
+    # MUNIT control files
     #======================================
     MU_CTL="${MU_MUNIT_ROOT}/ctl"
+    MU_TMP="/var/tmp/munit/tmp"
+    MU_MUNIT_MAP="${MU_TMP}/mu_test_map"
 
     #======================================
     # Temporary runtime files
     #======================================
-    MU_MUSE_MAP="${MU_TMP}/mu_muse_map"
-    MU_MUNIT_MAP="${MU_TMP}/mu_test_map"
     MU_TEST_LOG="${MU_TMP}/mu_test_log"
     MU_TEST_BUF="${MU_TMP}/mu_test_buf"
     MU_ERROR_BUF="${MU_TMP}/mu_error_buf"
@@ -90,12 +73,14 @@ set -a
 
     TESTFILE=""
 
+    #======================================
+    # Run Array for Test names
+    #======================================
     declare -a MU_RUN_ORDER
     MU_RUN_INDEX=0
     MU_NUM_TESTS=0
     MU_ERROR_INDEX=0
     MU_FAIL_INDEX=0
-
 
     #======================================
     # Reporting
@@ -131,7 +116,6 @@ usage()
 ## Date         :   02/08/2015
 ## Args         :   1 - file name
 ##                  2 - Variable name for return value
-##                  3 - MUSE | MUNIT Optional filter
 ## Status       :   Reviewed    [n]
 ##                  Tested      [n]
 ##                  Released    [n]
@@ -140,31 +124,17 @@ mu_find_file()
 {
     [[ -n "${1}" ]] || die "Usage. Arg[1]. File name expected  (${FUNCNAME})"
     [[ -n "${2}" ]] || die "Usage. Arg[2]. Variable name expected  (${FUNCNAME})"
-    local FILTER=${3:-MUNIT} MAPS=""
+    local FPATH=
     [[ -r "${MU_MUNIT_MAP}" ]] || die "Failed to find readable MUNIT map file (${MU_MUNIT_MAP})  (${FUNCNAME})"
 
-    if [[ $# -ne 3 ]]
-    then
-        MAPS="${MU_MUNIT_MAP} ${MU_MUSE_MAP}"
-    elif [[ "${FILTER}" == "MUNIT" ]]
-    then
-        MAPS="${MU_MUNIT_MAP}"
-    elif [[ "${FILTER}" == "MUSE" ]]
-    then
-        MAPS="${MU_MUSE_MAP}"
-    fi
-
-    for MAP in ${MAPS}
+    while read FPATH
     do
-        while read FPATH
-        do
-            if [[ "$(basename ${FPATH})" == "${1}" ]] 
-            then
-                eval ${2}='"${FPATH}"'
-                break
-            fi
-        done < "${MAP}"
-    done
+        if [[ "$(basename ${FPATH})" == "${1}" ]] 
+        then
+            eval ${2}="${FPATH}"
+            break
+        fi
+    done < "${MU_MUNIT_MAP}"
 }
 ##############################################################
 ##
@@ -185,7 +155,7 @@ include()
     #======================================
     # Find the file 
     #======================================
-    mu_find_file "${1}" FILE MUNIT
+    mu_find_file "${1}" FILE 
 
     [[ -r "${FILE}" ]] || die "Include library (${FILE}) not a readable file (${FUNCNAME})"
     source "${FILE}" || die "Include failed for library (${FILE}) (${FUNCNAME})"
@@ -214,6 +184,8 @@ mu_get_tmp_file()
         FILE="${MU_TMP}/${1}.${RANDOM}"
     done
 
+    :>"${FILE}"
+
     eval ${2}='"${FILE}"'
 }
 ##############################################################
@@ -239,8 +211,8 @@ mu_clean_file()
     # Name can be basename or FQN. If base 
     # then find it
     #======================================
-    [[ -f "${1}" ]] || mu_find_file "${1}" SRC MUNIT
-    [[ -f "${2}" ]] || mu_find_file "${2}" DST MUNIT
+    [[ -f "${1}" ]] || mu_find_file "${1}" SRC
+    [[ -f "${2}" ]] || mu_find_file "${2}" DST
 
     #======================================
     # Clean the file of comments etc.
@@ -339,9 +311,11 @@ mu_log_line()
 ##############################################################
 mu_create_map_files()
 {
-    find "${MU_MUSE_DEV_ROOT}" -type f > "${MU_MUSE_MAP}" 2>/dev/null || die "Find failed for (${MU_MUSE_DEV_ROOT}) (munit)"
-    find "${MU_MUSE_ROOT}" -type f >> "${MU_MUSE_MAP}" 2>/dev/null || die "Find failed for (${MU_MUSE_ROOT}) (munit)"
-    find "${MU_MUNIT_ROOT}" -type f > "${MU_MUNIT_MAP}" 2>/dev/null || die "Find failed for (${MU_MUNIT_MAP}) (munit)"
+    local DIR
+    for DIR in ${MU_MAP_DIRS[@]}
+    do
+        find ${DIR} -type f >> "${MU_MUNIT_MAP}" 2>/dev/null || die "Find failed for (${DIR}) (munit)"
+    done
 }
 ##############################################################
 ##
